name = "NAFPack"
version = "VERSION"
license = "MIT"
author = "Jules Minard"
maintainer = "https://github.com/Minard-Jules/NAFPack/issues"
copyright = "Copyright 2023, Jules Minard"
description = "Numerical Analysis in Fortran Package"
keywords = ["NAFPack"]
homepage = "https://github.com/Minard-Jules/NAFPack"


[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["fftw3", "fftw3_omp"]

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "default"

[dependencies]
openmp = "*"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.branch = "main"