name = "NAFPack"
version = "0.1.0"
license = "MIT"
author = "Jules Minard"
maintainer = "minard.jules@yahoo.com"
copyright = "Copyright 2023-2025, Jules Minard"
description = "Numerical Analysis in Fortran Package"
keywords = ["NAFPack", "numerical-analysis", "linear-algebra", "fortran", "performance"]
homepage = "https://github.com/Minard-Jules/NAFPack"


[build]
auto-executables = false
auto-tests = true
auto-examples = true
link = ["fftw3", "fftw3_omp", "blas", "lapack"]

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "default"

[dependencies]
openmp = "*"