A_QR – NAFPack
A_QR Function
9 statements
Source File
public function A_QR(A, b, method) result(x)
QR decomposition method
This function implements the QR decomposition method for solving linear systems. It allows the user to choose the method for QR decomposition (e.g., Householder).
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: A
real(kind=dp), intent(in), DIMENSION(:) :: b
character(len=*), intent(in), optional :: method
Return Value real(kind=dp), DIMENSION(SIZE(A, 1))
Calls
Called by
Source Code
    FUNCTION A_QR(A, b, method) RESULT(x)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: A
        REAL(dp), DIMENSION(:), INTENT(IN) :: b
        CHARACTER(LEN = *), OPTIONAL, INTENT(IN) :: method
        REAL(dp), DIMENSION(SIZE(A, 1)) :: x
        REAL(dp), DIMENSION(SIZE(A, 1) ,SIZE(A, 2)) :: Q, R
        CALL QR_decomposition(A, method, Q, R)
        x = backward(R, MATMUL(TRANSPOSE(Q), b))
    END FUNCTION A_QR
Call graph
a_qr calls backward, qr_decomposition
qr_decomposition calls identity_n, rotation_matrix
rotation_matrix calls identity_n
direct_methode calls a_qr