backward – NAFPack
backward Function
11 statements
Source File
public function backward(U, y) result(x)
backward algorithm, solves the system where U is an upper triangular matrix and y is a vector
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: U
real(kind=dp), intent(in), DIMENSION(:) :: y
Return Value real(kind=dp), DIMENSION(SIZE(U, 1))
Called by
Source Code
    FUNCTION backward(U, y) RESULT(x)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: U
        REAL(dp), DIMENSION(:), INTENT(IN) :: y
        REAL(dp), DIMENSION(SIZE(U, 1)) :: x
        INTEGER :: i, N
        N = SIZE(U, 1)
        x(N) = y(N) / U(N, N)
        DO i = N-1, 1, -1
            x(i) = (y(i) - DOT_PRODUCT(U(i, i+1:N), x(i+1:N))) / U(i, i)
        END DO
    END FUNCTION backward
Call graph
a_ldl_cholesky calls backward
a_ldu calls backward
a_lu calls backward
a_qr calls backward
cholesky calls backward
gauss calls backward
ilu_preconditioner calls backward
sip_icf calls backward
sip_ilu calls backward
direct_methode calls a_ldl_cholesky, a_ldu, a_lu, a_qr, cholesky, gauss
iterative_methods calls sip_icf, sip_ilu