Cholesky – NAFPack
Cholesky Function
19 statements
Source File
public function Cholesky(A, b, check) result(x)
Cholesky method
This function implements the Cholesky decomposition method for solving linear systems.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(: ,:) :: A
real(kind=dp), intent(in), DIMENSION(:) :: b
logical, intent(in), optional :: check
Return Value real(kind=dp), DIMENSION(SIZE(A,1))
Calls
Called by
Source Code
    FUNCTION Cholesky(A, b, check) RESULT(x)
        REAL(dp),DIMENSION(: ,:), INTENT(IN) :: A
        REAL(dp),DIMENSION(:), INTENT(IN) :: b
        LOGICAL, OPTIONAL, INTENT(IN) :: check
        REAL(dp),DIMENSION(SIZE(A,1)) :: x
        REAL(dp),DIMENSION(SIZE(A, 1), SIZE(A, 1)) :: L
        REAL(dp),DIMENSION(SIZE(A, 1)) :: y, lambda
        LOGICAL :: do_check = .TRUE.
        IF(PRESENT(check)) do_check = check
        IF(do_check) THEN
            PRINT*, "Checking if the matrix A is positive definite and symmetric"
            CALL Eigen(A, lambda, method = "Power_iteration")
            IF(MINVAL(lambda) < 0) STOP "ERROR :: A is not a definite matrix (Cholesky)"
            IF(MAXVAL(ABS(A - TRANSPOSE(A))) > epsi) STOP "ERROR :: A is not symmetric (Cholesky)"
        END IF
        CALL Cholesky_decomposition(A, L)
        y = forward(L, b)
        x = backward(TRANSPOSE(L), y)
    END FUNCTION Cholesky
Call graph
cholesky calls backward, cholesky_decomposition, eigen, forward
eigen calls identity_n, normalise, qr_decomposition
normalise calls norm_2
qr_decomposition calls identity_n, rotation_matrix
rotation_matrix calls identity_n
direct_methode calls cholesky