Diag – NAFPack
Diag Function
7 statements
Source File
public function Diag(A) result(D)
function that extracts the diagonal of a matrix where is a vector containing the diagonal elements of the matrix .
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: A
Return Value real(kind=dp), DIMENSION(size(A, 1))
Called by
Source Code
    FUNCTION Diag(A) RESULT(D)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: A
        REAL(dp), DIMENSION(size(A, 1)) :: D
        INTEGER :: i, N
        N = size(A, 1)
        FORALL (i=1:N) D(i) = A(i, i)
    END FUNCTION Diag
Call graph
calculate_gauss_seidel_preconditioner calls diag
calculate_jacobi_preconditioner calls diag
calculate_jor_preconditioner calls diag
calculate_sor_preconditioner calls diag
is_non_zero_diagonal calls diag