Direct_methode – NAFPack
Direct_methode Function
45 statements
Source File
public function Direct_methode(A, b, method, pivot_method, check) result(x)
Direct method for solving linear systems This function allows you to choose the direct method for solving the linear system. It supports various methods:
Gaussian elimination
LU decomposition
LDU decomposition
Cholesky decomposition
Alternative Cholesky decomposition
QR decomposition (Householder, Givens, Classical Gram-Schmidt, Modified Gram-Schmidt)
TDMA (Thomas algorithm)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(: ,:) :: A
real(kind=dp), intent(in), DIMENSION(:) :: b
character(len=*), intent(in), optional :: method
character(len=*), intent(in), optional :: pivot_method
logical, intent(in), optional :: check
Return Value real(kind=dp), DIMENSION(SIZE(A,1))
Calls
Source Code
    FUNCTION Direct_methode(A, b, method, pivot_method, check) RESULT(x)
        CHARACTER(LEN = *), OPTIONAL, INTENT(IN) :: method
        CHARACTER(LEN = *), OPTIONAL, INTENT(IN) :: pivot_method
        REAL(dp),DIMENSION(: ,:), INTENT(IN) :: A
        REAL(dp),DIMENSION(:), INTENT(IN) :: b
        LOGICAL, OPTIONAL, INTENT(IN) :: check
        REAL(dp),DIMENSION(SIZE(A,1)) :: x
        REAL(dp),DIMENSION(SIZE(A,1),SIZE(A,2)) :: Ainv
        REAL(dp),DIMENSION(SIZE(A,1)+1) :: c
        INTEGER :: N
        LOGICAL :: do_check = .TRUE., success
        IF(PRESENT(check)) do_check = check
        N = SIZE(A, 1)
        IF(SIZE(A, 2) /= N) STOP "ERROR :: Matrix A not square"
        IF(SIZE(b, 1) /= N) STOP "ERROR :: Dimension mismatch in linear system"
        IF (.NOT. PRESENT(method)) THEN
            PRINT*, "WARNING :: No method specified for linear system, using LU decomposition"
            x = A_LU(A, b)
        END IF
        IF(method == "Gauss")THEN
            x = Gauss(A, b, pivot_method=pivot_method)
        ELSE IF(method == "A_LU")THEN
            x = A_LU(A, b)
        ELSE IF(method == "A_LDU")THEN
            x = A_LDU(A, b)
        ELSE IF(method == "Cholesky")THEN
            x = Cholesky(A, b, check = do_check)
        ELSE IF(method == "A_LDL_Cholesky")THEN
            x = A_LDL_Cholesky(A, b, check = do_check)
        ELSE IF (INDEX(method, "QR") == 1) THEN
            x = A_QR(A, b, method = method)
        ELSE IF(method == "TDMA")THEN
            x = TDMA(A, b, check = do_check)
        ELSE IF(method == "Faddeev_Leverrier") THEN
            CALL Faddeev_Leverrier(A, c, Ainv = Ainv, success = success, check = do_check)
            IF (.NOT. success) THEN
                PRINT*, "WARNING :: Faddeev-Leverrier method failed, using LU decomposition instead"
                x = A_LU(A, b)
            ELSE
                x = MATMUL(Ainv, b)
            END IF
        ELSE
            STOP "ERROR : Wrong method for linear system (direct_methode)"
        END IF
    END FUNCTION Direct_methode
Call graph
direct_methode calls a_ldl_cholesky, a_ldu, a_lu, a_qr, cholesky, faddeev_leverrier, gauss, tdma
a_ldl_cholesky calls backward, eigen, forward, ldl_cholesky_decomposition
a_ldu calls backward, forward, ldu_decomposition
a_lu calls backward, forward, lu_decomposition
a_qr calls backward, qr_decomposition
cholesky calls backward, cholesky_decomposition, eigen, forward
faddeev_leverrier calls identity_n, trace
gauss calls backward, identity_n, rotation_matrix
eigen calls identity_n, qr_decomposition, normalise
ldl_cholesky_decomposition calls identity_n
qr_decomposition calls identity_n, rotation_matrix
rotation_matrix calls identity_n
normalise calls norm_2