forward – NAFPack
forward Function
11 statements
Source File
public function forward(L, b) result(y)
forward algorithm, solves the system where L is a lower triangular matrix and b is a vector
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: L
real(kind=dp), intent(in), DIMENSION(:) :: b
Return Value real(kind=dp), DIMENSION(SIZE(L, 1))
Called by
Source Code
    FUNCTION forward(L, b) RESULT(y)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: L
        REAL(dp), DIMENSION(:), INTENT(IN) :: b
        REAL(dp), DIMENSION(SIZE(L, 1)) :: y
        INTEGER :: i, N
        N = SIZE(L, 1)
        y(1) = b(1) / L(1, 1)
        DO i = 2,N
            y(i) = (b(i) - DOT_PRODUCT(L(i,1:i-1), y(1:i-1))) / L(i,i)
        END DO
    END FUNCTION forward
Call graph
a_ldl_cholesky calls forward
a_ldu calls forward
a_lu calls forward
cholesky calls forward
ilu_preconditioner calls forward
sip_icf calls forward
sip_ilu calls forward
direct_methode calls a_ldl_cholesky, a_ldu, a_lu, cholesky
iterative_methods calls sip_icf, sip_ilu