Gauss – NAFPack
Gauss Function
57 statements
Source File
public function Gauss(A, b, pivot_method) result(x)
Gaussian elimination method
This function implements the Gaussian elimination method for solving linear systems. It performs partial or total pivoting based on the user's choice.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: A
real(kind=dp), intent(in), DIMENSION(:) :: b
character(len=*), intent(in), optional :: pivot_method
Return Value real(kind=dp), DIMENSION(SIZE(A,1))
Calls
Called by
Source Code
    FUNCTION Gauss(A, b, pivot_method) RESULT(x)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: A
        REAL(dp), DIMENSION(:), INTENT(IN) :: b
        CHARACTER(LEN = *), OPTIONAL, INTENT(IN) :: pivot_method
        REAL(dp), DIMENSION(SIZE(A,1)) :: x
        REAL(dp), DIMENSION(SIZE(A, 1), SIZE(A, 2)) :: A_tmp, P, Q, Q_final
        REAL(dp), DIMENSION(SIZE(b)) :: b_tmp
        INTEGER, DIMENSION(1) :: vlmax_partial
        INTEGER, DIMENSION(2) :: vlmax_total
        REAL(dp) :: m , pivot
        INTEGER :: k, i, N, lmax, cmax
        A_tmp = A
        b_tmp = b
        N=SIZE(A_tmp, 1)
        Q_final = Identity_n(N)
        DO k = 1, N-1
            IF (.NOT. PRESENT(pivot_method)) THEN
                PRINT*, "WARNING :: No pivot method specified, using normal pivot"
            END IF
            IF(pivot_method == "partial") THEN
                ! Find the maximum absolute value in the column from row k to N
                vlmax_partial = MAXLOC(ABS(A_tmp(k:N, k)))
                lmax = vlmax_partial(1) + k - 1
                !calculate permutation matrix P
                P = Identity_n(N)
                IF (k /= lmax) THEN
                    P = rotation_matrix(P, [k, lmax])
                END IF
                A_tmp = MATMUL(P, A_tmp)
                b_tmp = MATMUL(P, b_tmp)
            ELSE IF(pivot_method == "total") THEN
                ! Find max abs element in submatrix
                vlmax_total = MAXLOC(ABS(A_tmp(k:N,k:N)))
                lmax = vlmax_total(1) + k - 1
                cmax = vlmax_total(2) + k - 1
                ! permute line if necessary
                P = Identity_n(N)
                IF (lmax /= k) THEN
                    P = rotation_matrix(P, [k, lmax])
                END IF
                ! permute column if necessary
                Q = Identity_n(N)
                IF (cmax /= k) THEN
                    Q = rotation_matrix(Q, [k, cmax])
                END IF
                Q_final = MATMUL(Q, Q_final)
                ! Apply permutations
                A_tmp = MATMUL(P, A_tmp)
                A_tmp = MATMUL(A_tmp, Q)
                b_tmp = MATMUL(P, b_tmp)
            END IF
            pivot = A_tmp(k, k)
            IF (ABS(pivot) < epsi) STOP "ERROR :: Near-zero pivot – matrix may be singular"
            DO i = k+1, N
                m = A_tmp(i, k) / pivot
                A_tmp(i, k) = 0
                ! Vectorized operation
                A_tmp(i, k+1:N) = A_tmp(i, k+1:N) - m * A_tmp(k, k+1:N)
                b_tmp(i) = b_tmp(i) - m * b_tmp(k)
            END DO
        END DO
        x = backward(A_tmp, b_tmp)
        IF (pivot_method == "total") x = MATMUL(Q_final, x)
    END FUNCTION Gauss
Call graph
gauss calls backward, identity_n, rotation_matrix
rotation_matrix calls identity_n
direct_methode calls gauss