Identity_n – NAFPack
Identity_n Function
17 statements
Source File
public function Identity_n(N, use_concurrent) result(Identity)
function that returns the identity matrix for a given size N
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
logical, intent(in), optional :: use_concurrent
Return Value real(kind=dp), DIMENSION(N, N)
Called by
Source Code
     FUNCTION Identity_n(N, use_concurrent) RESULT(Identity)
        INTEGER, INTENT(IN) :: N
        LOGICAL, INTENT(IN), OPTIONAL :: use_concurrent
        REAL(dp), DIMENSION(N, N) :: Identity
        INTEGER :: i
        LOGICAL :: concurrent_mode
        concurrent_mode = .FALSE.
        IF (PRESENT(use_concurrent)) concurrent_mode = use_concurrent
        Identity = 0.d0
        IF (concurrent_mode) THEN
            DO CONCURRENT (i = 1:N)
                Identity(i, i) = 1.0_dp
            END DO
        ELSE
            FORALL(i = 1:N) Identity(i, i) = 1.0_dp
        END IF
    END FUNCTION Identity_n
Call graph
eigen calls identity_n, qr_decomposition
faddeev_leverrier calls identity_n
ilu_decomposition calls identity_n
incomplete_cholesky_decomposition calls identity_n
is_orthogonal calls identity_n
ldl_cholesky_decomposition calls identity_n
qr_givens_decomposition calls identity_n, rotation_matrix
qr_gram_schmidt_classical_decomposition calls identity_n
qr_householder_decomposition calls identity_n
rotation_matrix calls identity_n
calculate_icf_preconditioner calls incomplete_cholesky_decomposition
calculate_ilu_preconditioner calls ilu_decomposition
is_spd calls eigen
qr_decomposition calls qr_givens_decomposition, qr_gram_schmidt_classical_decomposition, qr_householder_decomposition