IFFT_3D – NAFPack
IFFT_3D Function
13 statements
Source File
public function IFFT_3D(signal, method, threads) result(result)
Perform a 3D inverse Fast Fourier Transform on a signal
This function takes a signal and performs a inverse fast Fourier Transform using the specified method. The available methods are:
"FFTW_IFFT_3D": Fast Fourier Transform using FFTW
"FFTW_IFFT_3D" + threads: Fast Fourier Transform using FFTW with multithreading
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(inout), dimension(:, :, :) :: signal
character(len=*), intent(in) :: method
integer, intent(in), optional :: threads
Return Value complex(kind=dp), dimension(size(signal, 1), size(signal, 2), size(signal, 3))
Calls
Source Code
    function IFFT_3D(signal, method, threads) result(result)
        complex(dp), dimension(:, :, :), intent(inout) :: signal
        character(*), intent(in) :: method
        integer, optional, intent(in) :: threads
        complex(dp), dimension(size(signal, 1), size(signal, 2), size(signal, 3)) :: result
        if (method == "FFTW_IFFT_3D" .and. .not. present(threads)) then
            result = FFTW_IFFT_3D(signal)
        else if (method == "IFFTW_IFFT_3D" .and. present(threads)) then
            result = FFTW_IFFT_3D_threads(signal, threads)
        else
            stop "ERROR : Wrong method for IFFT_1D"
        end if
    end function IFFT_3D
Call graph
ifft_3d calls fftw_cleanup, fftw_cleanup_threads, fftw_destroy_plan, fftw_execute_dft, fftw_init_threads, fftw_plan_dft_3d, fftw_plan_with_nthreads