ILU_preconditioner – NAFPack
ILU_preconditioner Subroutine
12 statements
Source File
public subroutine ILU_preconditioner(r, z, A)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:) :: r
real(kind=dp), intent(out), DIMENSION(:) :: z
real(kind=dp), intent(in), DIMENSION(:, :) :: A
Calls
Source Code
    SUBROUTINE ILU_preconditioner(r, z, A)
        REAL(dp), DIMENSION(:), INTENT(IN) :: r
        REAL(dp), DIMENSION(:), INTENT(OUT) :: z
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: A
        REAL(dp), DIMENSION((SIZE(r))) :: y
        IF(.NOT. preconditioner_use%ILU) THEN
            CALL preconditioner_use%Allocate_ILU(SIZE(r))
            CALL preconditioner_use%Calculate_ILU(A)
        END IF
        y = forward(preconditioner_use%L_ilu, r)
        z = backward(preconditioner_use%U_ilu, y)
    END SUBROUTINE ILU_preconditioner
Call graph
ilu_preconditioner calls allocate_ilu, calculate_ilu, backward, forward
ilu_decomposition calls identity_n