is_SPD – NAFPack
is_SPD Function
22 statements
Source File
public function is_SPD(A, is_sym) result(is_spd_matrix)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: A
logical, intent(in), optional :: is_sym
Return Value logical
Calls
Source Code
    FUNCTION is_SPD(A, is_sym) RESULT(is_spd_matrix)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: A
        LOGICAL, OPTIONAL, INTENT(IN) :: is_sym
        REAL(dp), DIMENSION(SIZE(A, 1)) :: lambda
        LOGICAL :: is_spd_matrix
        IF (PRESENT(is_sym)) THEN
            IF (.NOT. is_sym) THEN
                is_spd_matrix = .FALSE.
                RETURN
            END IF
        ELSE IF (.NOT. is_symmetric(A)) THEN
            is_spd_matrix = .FALSE.
            RETURN
        END IF
        PRINT *, "Checking if the matrix is SPD..."
        CALL Eigen(A, lambda, method = "Power_iteration")
        IF(MINVAL(lambda) < 0) THEN
            is_spd_matrix = .FALSE.
        ELSE
            is_spd_matrix = .TRUE.
        END IF
    END FUNCTION is_SPD
Call graph
is_spd calls eigen, is_symmetric
eigen calls identity_n, normalise, qr_decomposition
is_symmetric calls is_square_matrix
normalise calls norm_2
qr_decomposition calls qr_givens_decomposition, qr_gram_schmidt_classical_decomposition, qr_gram_schmidt_modified_decomposition, qr_householder_decomposition
qr_givens_decomposition calls identity_n, rotation_matrix
qr_gram_schmidt_classical_decomposition calls identity_n
qr_householder_decomposition calls identity_n
rotation_matrix calls identity_n