is_square_matrix – NAFPack
is_square_matrix Function
6 statements
Source File
public function is_square_matrix(A) result(is_square)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: A
Return Value logical
Called by
Source Code
    FUNCTION is_square_matrix(A) RESULT(is_square)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: A
        LOGICAL :: is_square
        PRINT *, "Checking if the matrix is square..."
        is_square = (SIZE(A, 1) == SIZE(A, 2))
    END FUNCTION is_square_matrix
Call graph
is_diagonally_dominant calls is_square_matrix
is_non_zero_diagonal calls is_square_matrix
is_orthogonal calls is_square_matrix
is_symmetric calls is_square_matrix
is_tridiagonal calls is_square_matrix
is_spd calls is_symmetric