Iterative_methods – NAFPack
Iterative_methods Function
91 statements
Source File
public function Iterative_methods(A, b, method, omega, x_init, max_iter, tol, verbose) result(x)
Iterative method for solving linear systems This function allows you to choose the iterative method for solving the linear system. It supports various methods:
Jacobi
Gauss-Seidel
Successive Over-Relaxation (SOR)
strongly implicit procedure (SIP_ILU, SIP_ICF)
Symmetric Successive Over-Relaxation (SSOR)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: A
real(kind=dp), intent(in), DIMENSION(:) :: b
character(len=*), intent(in), optional :: method
real(kind=dp), intent(in), optional :: omega
real(kind=dp), intent(in), optional, DIMENSION(:) :: x_init
integer, intent(in), optional :: max_iter
real(kind=dp), intent(in), optional :: tol
type(Logger), optional :: verbose
Return Value real(kind=dp), DIMENSION(SIZE(A, 1))
Calls
Source Code
    FUNCTION Iterative_methods(A, b, method, omega, x_init, max_iter, tol, verbose) RESULT(x)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: A
        REAL(dp), DIMENSION(:), INTENT(IN) :: b
        REAL(dp), DIMENSION(:), OPTIONAL, INTENT(IN) :: x_init
        CHARACTER(LEN = *), OPTIONAL, INTENT(IN) :: method
        INTEGER, OPTIONAL, INTENT(IN) :: max_iter
        REAL(dp), OPTIONAL, INTENT(IN) :: omega, tol
        TYPE(Logger), OPTIONAL :: verbose
        REAL(dp), DIMENSION(:, :), ALLOCATABLE :: L, U
        REAL(dp), DIMENSION(SIZE(A, 1)) :: x
        REAL(dp), DIMENSION(SIZE(A, 1)) :: x0, x_new, residu
        REAL(dp) :: epsi_tol
        INTEGER :: k, max_iter_choice, N, alloc_stat
        CHARACTER(LEN=64) :: msg
        N = SIZE(A, 1)
        IF(SIZE(A, 2) /= N) STOP "ERROR :: Matrix A not square"
        IF (PRESENT(max_iter))THEN
            max_iter_choice = max_iter
        ELSE
            max_iter_choice = kmax
        END IF
        IF (PRESENT(x_init))THEN
            IF (SIZE(x_init, 1) /= SIZE(A, 1)) STOP "ERROR : Dimension of x_init different from A"
            x0 = x_init
        ELSE
            x0 = 0.d0
        END IF
        IF (PRESENT(tol)) THEN
            epsi_tol = tol
        ELSE
            epsi_tol = epsi
        END IF
        IF (method == "SIP_ILU")THEN
            ALLOCATE(L(SIZE(A,1),SIZE(A,2)), U(SIZE(A,1),SIZE(A,2)), stat=alloc_stat)
            IF (alloc_stat /= 0) STOP "ERROR :: Memory allocation failed for L or U in SIP_ILU"
            residu = b - MATMUL(A, x0)
            CALL ILU_decomposition(A, L, U)
        ELSE IF (method == "SIP_ICF")THEN
            ALLOCATE(L(SIZE(A,1),SIZE(A,2)), stat=alloc_stat)
            IF (alloc_stat /= 0) STOP "ERROR :: Memory allocation failed for L or U in SIP_ICF"
            residu = b - MATMUL(A, x0)
            CALL Incomplete_Cholesky_decomposition(A, L)
        ELSE IF (INDEX(method, "Richardson") == 1)THEN
            residu = b - MATMUL(A, x0)
        END IF
        DO k = 1, max_iter_choice
            IF(k == max_iter_choice) THEN
                PRINT*, "WARNING :: non-convergence of the iterative method "//method
                PRINT*, "Residual norm: ", NORM2(residu)
                EXIT
            END IF
            IF(method == "Jacobi")THEN
                CALL Jacobi(A, b , x0, x_new)
            ELSE IF(method == "Gauss_Seidel")THEN
                CALL Gauss_Seidel(A, b, x0, x_new)
            ELSE IF(method == "SOR")THEN
                CALL SOR(A, b, x0, x_new, Get_Omega(method, omega))
            ELSE IF(method == "JOR")THEN
                CALL JOR(A, b, x0, x_new, Get_Omega(method, omega))
            ELSE IF(method == "SIP_ILU") THEN
                CALL SIP_ILU(L, U, x0, x_new, residu, Get_Omega(method, omega))
            ELSE IF(method == "SIP_ICF") THEN
                CALL SIP_ICF(L, x0, x_new, residu, Get_Omega(method, omega))
            ELSE IF(method == "SSOR")THEN
                CALL SSOR(A, b, x0, x_new, Get_Omega(method, omega))
            ELSE IF(method == "Richardson_Stationary")THEN
                CALL Richardson(x0, x_new, residu, Get_Omega(method, omega), method)
            ELSE IF(method == "Richardson_ILU_Preconditioned")THEN
                CALL Richardson(x0, x_new, residu, Get_Omega(method, omega), method, preconditioner_choice=ILU_preconditioner, A=A)
            ELSE
                STOP "ERROR : Wrong method for linear system (Iterative_methods)"
            END IF
            residu = b - MATMUL(A, x_new)
            IF (PRESENT(verbose)) THEN
                verbose%step = k
                WRITE(msg, '(A,I3,A,ES14.7)') "Iter ", k, " | Norm residu: ", NORM2(residu)
                CALL verbose%log(msg)
            END IF
            IF (NORM2(residu) < epsi_tol) EXIT
            x0 = x_new
        END DO
        IF (method == "SIP_ILU")THEN
            DEALLOCATE(L, U)
        ELSE IF (method == "SIP_ICF")THEN
            DEALLOCATE(L)
        ELSE IF (INDEX(method, "Richardson") == 1) THEN
            preconditioner_use = preconditioner(.FALSE.)
            IF (method == "Richardson_ILU_Preconditioned") CALL preconditioner_use%DEALLOCATE_ILU()
        END IF
        x = x_new
    END FUNCTION Iterative_methods
Call graph
iterative_methods calls deallocate_ilu, gauss_seidel, ilu_decomposition, incomplete_cholesky_decomposition, jacobi, jor, richardson, sip_icf, sip_ilu, sor, ssor
ilu_decomposition calls identity_n
incomplete_cholesky_decomposition calls identity_n
sip_icf calls backward, forward
sip_ilu calls backward, forward