normalise – NAFPack
normalise Function
5 statements
Source File
public function normalise(a) result(result)
function that normalises a real vector a to make it a unit vector, where
Arguments
Type Intent Optional Attributes Name
real(kind=dp), DIMENSION(:) :: a
Return Value real(kind=dp), DIMENSION(SIZE(a))
Calls
Called by
Source Code
    FUNCTION normalise(a) RESULT(result)
        REAL(dp), DIMENSION(:) :: a
        REAL(dp), DIMENSION(SIZE(a)) :: result
        result = a / norm_2(a)
    END FUNCTION normalise
Call graph
normalise calls norm_2
eigen calls normalise
a_ldl_cholesky calls eigen
cholesky calls eigen
direct_methode calls a_ldl_cholesky, cholesky