norm_2 – NAFPack
norm_2 Function
5 statements
Source File
public function norm_2(a) result(result)
function that calculates the Euclidean norm (L2 norm) of a vector , where where is the dimension of the real vector .
Arguments
Type Intent Optional Attributes Name
real(kind=dp), DIMENSION(:) :: a
Return Value real(kind=dp)
Called by
Source Code
    FUNCTION norm_2(a) RESULT(result)
        REAL(dp), DIMENSION(:) :: a
        REAL(dp) :: result
        result = SQRT(DOT_PRODUCT(a, a))
    END FUNCTION norm_2
Call graph
normalise calls norm_2
eigen calls normalise
a_ldl_cholesky calls eigen
cholesky calls eigen
direct_methode calls a_ldl_cholesky, cholesky