QR_decomposition – NAFPack
QR_decomposition Subroutine
14 statements
Source File
public subroutine QR_decomposition(A, method, Q, R)
QR decomposition of a matrix A using various methods This subroutine performs QR decomposition of a given matrix A using the specified method (Householder, Givens, Classical Gram-Schmidt, or Modified Gram-Schmidt). The output matrices Q is an orthogonal matrix and R is an upper triangular matrix.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: A
character(len=*), intent(in), optional :: method
real(kind=dp), intent(out), DIMENSION(SIZE(A, 1) ,SIZE(A, 2)) :: Q
real(kind=dp), intent(out), DIMENSION(SIZE(A, 1) ,SIZE(A, 2)) :: R
Calls
Called by
Source Code
    SUBROUTINE QR_decomposition(A, method, Q, R)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: A
        CHARACTER(LEN = *), OPTIONAL, INTENT(IN) :: method
        REAL(dp), DIMENSION(SIZE(A, 1) ,SIZE(A, 2)), INTENT(OUT) :: Q, R
        IF(method == "QR_Householder")THEN
            CALL QR_Householder_decomposition(A, Q, R)
        ELSE IF(method == "QR_Givens")THEN
            CALL QR_Givens_decomposition(A, Q, R)
        ELSE IF(method == "QR_Gram_Schmidt_Classical")THEN
            CALL QR_Gram_Schmidt_Classical_decomposition(A, Q, R)
        ELSE IF(method == "QR_Gram_Schmidt_Modified")THEN
            CALL QR_Gram_Schmidt_Modified_decomposition(A, Q, R)
        END IF
    END SUBROUTINE QR_decomposition
Call graph
qr_decomposition calls qr_givens_decomposition, qr_gram_schmidt_classical_decomposition, qr_gram_schmidt_modified_decomposition, qr_householder_decomposition
qr_givens_decomposition calls identity_n, rotation_matrix
qr_gram_schmidt_classical_decomposition calls identity_n
qr_householder_decomposition calls identity_n
rotation_matrix calls identity_n
eigen calls qr_decomposition
is_spd calls eigen