rotation_matrix – NAFPack
rotation_matrix Function
17 statements
Source File
public function rotation_matrix(A, rotation) result(G)
Function to create a rotation matrix
This function generates a rotation matrix G based on the input matrix A and the specified rotation indices.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:, :) :: A
integer, intent(in), DIMENSION(2) :: rotation
Return Value real(kind=dp), DIMENSION(SIZE(A, 1),SIZE(A, 2))
Calls
Called by
Source Code
    FUNCTION rotation_matrix(A,rotation) RESULT(G)
        REAL(dp), DIMENSION(:, :), INTENT(IN) :: A
        INTEGER, DIMENSION(2), INTENT(IN) :: rotation
        REAL(dp), DIMENSION(SIZE(A, 1),SIZE(A, 2)) :: G
        REAL(dp) :: frac, val_1, val_2
        INTEGER :: i, j
        i = rotation(1)
        j = rotation(2)
        G = Identity_n(SIZE(A, 1))
        val_1 = A(j, j)
        val_2 = A(i, j)
        frac = SQRT(val_1**2 + val_2**2)
        G(i,i) = val_1 / frac
        G(j,j) = val_1 / frac
        G(i,j) = - val_2 / frac
        G(j,i) = val_2 / frac
    END FUNCTION rotation_matrix
Call graph
rotation_matrix calls identity_n
gauss calls rotation_matrix
qr_decomposition calls rotation_matrix
a_qr calls qr_decomposition
direct_methode calls gauss, a_qr, a_ldl_cholesky, cholesky
eigen calls qr_decomposition
a_ldl_cholesky calls eigen
cholesky calls eigen