FFT_3D – NAFPack
FFT_3D Function
13 statements
Source File
public function FFT_3D(signal, method, threads) result(result)
Perform a 3D Fast Fourier Transform on a signal
This function takes a signal and performs a Fourier Transform using the specified method. The available methods are: - "FFTW_FFT_3D": Fast Fourier Transform using FFTW - "FFTW_FFT_3D" + threads: Fast Fourier Transform using FFTW with multithreading
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(inout), DIMENSION(:, :, :) :: signal
character(len=*), intent(in) :: method
integer, intent(in), optional :: threads
Return Value complex(kind=dp), DIMENSION(SIZE(signal, 1) ,SIZE(signal, 2), SIZE(signal, 3))
Calls
Source Code
    FUNCTION FFT_3D(signal, method, threads) RESULT(result)
        COMPLEX(dp), DIMENSION(:, :, :), INTENT(INOUT) :: signal
        CHARACTER(*), INTENT(IN) :: method
        INTEGER, OPTIONAL, INTENT(IN) :: threads
        COMPLEX(dp), DIMENSION(SIZE(signal, 1) ,SIZE(signal, 2), SIZE(signal, 3)) :: result
        IF(method == "FFTW_FFT_3D" .AND. .NOT. PRESENT(threads))THEN
            result = FFTW_FFT_3D(signal)
        ELSE IF (method == "FFTW_FFT_3D" .AND. PRESENT(threads))THEN
            result = FFTW_FFT_3D_threads(signal, threads)
        ELSE
            STOP "ERROR : Wrong method for FFT_2D"
        END IF
    END FUNCTION FFT_3D
Call graph
fft_3d calls fftw_cleanup_threads, fftw_destroy_plan, fftw_execute_dft, fftw_init_threads, fftw_plan_dft_3d, fftw_plan_with_nthreads