fftw_destroy_plan – NAFPack
fftw_destroy_plan Interface
515 statements
Source File
interface
Called by
public subroutine fftw_destroy_plan(p) bind(C, name='fftw_destroy_plan')
Arguments
Type Intent Optional Attributes Name
type(C_PTR), value :: p
Call graph
fft_1d calls fftw_destroy_plan
fft_2d calls fftw_destroy_plan
fft_3d calls fftw_destroy_plan
ifft_1d calls fftw_destroy_plan
ifft_2d calls fftw_destroy_plan
ifft_3d calls fftw_destroy_plan